
# API for signup
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "Manju",
    "password": "Password@123",
    "email": "Manju@gmail.com"
}

###

# API to list all Transactions -- but we get all transactions firm all users

GET http://127.0.0.1:8000/api/transactions/
Authorization: Token 6bb16db339cbd01f41bc28547606e38dd5c97f82

###

# API to list transaction with owner

POST http://127.0.0.1:8000/api/transactions/
Content-Type: application/json
Authorization: Token 6bb16db339cbd01f41bc28547606e38dd5c97f82

{
    "title":"Home",
    "amount":30000
}

###

GET http://127.0.0.1:8000/api/transactions/5/
Authorization: Basic python:Password@123

###
# API to update transaction

PUT http://127.0.0.1:8000/api/transactions/5/
Content-Type: application/json
Authorization: Basic django:Password@123

{
  "title": "Home",
  "amount": 80000.0,
  "category": "Rent",
  "payment_method": "UPI",
  "priority": "NEED"
}


###

# API for token from inbuilt authtoken app.

POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "django",
  "password": "Password@123"
}

















